name: Test Python App

on:
  push:
    branches: ["**"]

jobs:
  ci:
    run-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: install
        uses: 
          python -m pip install –upgrade pip
          pip install -r requirements.txt

      - name: tests
        uses: python -m pytest tests/
